### ISSUE TITLE
Migrate Settings from v11 to v12

### ISSUE THREAD

**Issue by parts4heat** [parts4heat/odoo#1]

**Comment by parts4heat** [comment]
Installed Apps
Discuss - created #sales and #warehouse channels.
Contacts - imported States/Country gap record so past Customer information could be imported.

**Comment by parts4heat** [comment]
CRM, Sales, Website.
Need:  Pricelists, eCommerce Recovery Email Template, Default Terms and Conditions

**Comment by bweekes** [comment]
All apps and configurations are migrated over. Also installed missing products and price lists.

**Comment by bweekes** [comment]
Closing this issue.
